### PR TITLE
syntax highlight in traceback view

### PR DESCRIPTION
**Pull request by stormandco**

### CODE REVIEW

**Comment by stormandco** [comment]
It works, but not finished yet. Some code should be removed.

To highlight current line I'm splitting source code to lines and wrapping it with `span.current`. Looks like a hack, but works.
Also, highlight.js doesn't support line numbers, which are useful in this case, I think. So, I can try to add them somehow. Or maybe it would be better to try [prinsm.js](http://prismjs.com/), which has line numbers and line highlight?

**Comment by jettify** [comment]
prism.js looks like actively maintained, so why not

**Comment by asvetlov** [comment]
I've never used prism but was happy with highlight.js.
Anyway, if you guys choose prism.js I have no objections.

**Comment by jettify** [comment]
@stormandco sorry of delay I will review this PR as soon as resolve issue with interactive debugger

**Comment by stormandco** [comment]
@jettify no problem. I think it needs some cleanup in tbtools.py
Will try to do this on the weekends

**Comment by jettify** [comment]
tbtools.py very dirty port that handles interactive console logic, tracebacks etc, ported from flask to pyramid_debugtoolbar and then here... I have not touched that much because I managed to make it work. To rewrite that chunk is bit tricky task.

**Comment by stormandco** [comment]
At least class `Line`, `SOURCE_TABLE_HTML`, `SOURCE_LINE_HTML` strings, and some methods in `Frame` should be removed

**Comment by jettify** [comment]
sure, if it simplifies code greatly, it would be easer to refactor interactive console as result get rid of thread locals

**Comment by stormandco** [comment]
@jettify @asvetlov 
Could you please review this PR?

**Comment by asvetlov** [comment]
I'll take a look in few days.

**Comment by asvetlov** [comment]
Sorry for long delay.
Thank you for both the patch and your patience.

**Pull request merged**
