### PR TITLE
setup() adds middleware

### LINKED ISSUE #33: setup() should add the middleware
IMO, adding necessary middleware is the responsibility of a plugin's `setup()` function.

Current:
```python
import aiohttp_debugtoolbar
app = web.Application(middlewares=[aiohttp_debugtoolbar.middleware])
aiohttp_debugtoolbar.setup(app)
```

Proposed:

```python
import aiohttp_debugtoolbar
app = web.Application()
aiohttp_debugtoolbar.setup(app)
```

### PR DESCRIPTION
**Pull request by sloria**
closes #33

### CODE REVIEW

**Comment by jettify** [comment]
Looks good! But I think we need to add some sort of check if `middleware` was inserted to `aiohttp.web.Application` before. So following case also can works:
```python
app = Application(loop=loop, middlewares=[aiohttp_debugtoolbar.middleware])
aiohttp_debugtoolbar.setup(app)
```

**Comment by sloria** [comment]
Updated. Let me know if any further changes need to be made.

**Comment by asvetlov** [comment]
LGTM

**Comment by jettify** [comment]
Thanks!

**Pull request merged**
